<?php require('inc/header.php') ?>

<link rel="stylesheet" href="css/inner.css">

<section class="book-form inner__page" style="background-image:url('images/4.jpg')">
   <div class="container">
      <div class="title-wrapper">
         <h2>Book Your trip Here</h2>
      </div>
      <form action="#" method="post" class="form form-horizontal ">
         <div class="col-12">
            <div class="book-form-title">
               <h3> <span>1</span> Trip Information</h3>
            </div>
         </div>
         <div class="row">
            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Trip Name</label>
               <input type="text" name="destination_id" class="form-control form-control-sm" value="Annapurna Circuit Trek" disabled="">

            </div>
            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Number Of Traveller</label>
               <div class="custom-select book-select">
                  <div class="select">
                     <select name="number_of_person" class="select-hidden">

                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>

                        <option value="other">Above 12</option>
                     </select>
                     <div class="select-styled">1</div>
                     <ul class="select-options">
                        <li rel="1">1</li>
                        <li rel="2">2</li>
                        <li rel="3">3</li>
                        <li rel="4">4</li>
                        <li rel="5">5</li>
                        <li rel="6">6</li>
                        <li rel="7">7</li>
                        <li rel="8">8</li>
                        <li rel="9">9</li>
                        <li rel="10">10</li>
                        <li rel="11">11</li>
                        <li rel="12">12</li>
                        <li rel="other">Above 12</li>
                     </ul>
                  </div>
               </div>
            </div>

            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Type</label>
               <div class="custom-select book-select">
                  <div class="select">
                     <select name="type" class="select-hidden">
                        <option value="0"></option>
                        <option value="Private">Private</option>
                        <option value="Group">Group</option>
                     </select>
                     <div class="select-styled"></div>
                     <ul class="select-options">
                        <li rel="0"></li>
                        <li rel="Private">Private</li>
                        <li rel="Group">Group</li>
                     </ul>
                  </div>
               </div>
            </div>

            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Arrival Date</label>
               <input type="date" name="arrival_date" placeholder="" id="arrive_index">
            </div>
            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Departure Date</label>
               <input type="date" id="departure_top" name="departure_date" placeholder="departure_top">
            </div>
         </div>
         <div class="col-12">
            <div class="book-form-title">
               <h3> <span>2</span> Personal Information</h3>
            </div>
         </div>
         <div class="row">
            <div class="col-lg-6 col-md-6 col-12">
               <label for="">Full Name</label>
               <input type="text" name="full_name" placeholder="">
            </div>
            <div class="col-lg-6 col-md-6 col-12">
               <label for="">Email</label>
               <input type="email" name="email" placeholder="">
            </div>
            <div class="col-lg-6 col-md-6 col-12">
               <label for="">Phone Number</label>
               <input type="text" name="mobile_no" placeholder="">
            </div>
            <div class="col-lg-6 col-md-6 col-12">
               <label for="">Country</label>
               <div class="custom-select book-select">
                  <div class="select"><select name="country" class="select-hidden">
                        <option>Select Country</option>
                        <option value="Afghanistan">Afghanistan</option>
                        <option value="Albania">Albania</option>
                        <option value="Algeria">Algeria</option>
                        <option value="American Samoa">American Samoa</option>
                        <option value="Andorra">Andorra</option>
                        <option value="Angola">Angola</option>
                        <option value="Anguilla">Anguilla</option>
                        <option value="Antarctica">Antarctica</option>
                        <option value="Antigua And Barbuda">Antigua And Barbuda</option>
                        <option value="Argentina">Argentina</option>
                        <option value="Armenia">Armenia</option>
                        <option value="Aruba">Aruba</option>
                        <option value="Australia">Australia</option>
                        <option value="Austria">Austria</option>
                        <option value="Azerbaijan">Azerbaijan</option>
                        <option value="Bahamas The">Bahamas The</option>
                        <option value="Bahrain">Bahrain</option>
                        <option value="Bangladesh">Bangladesh</option>
                        <option value="Barbados">Barbados</option>
                        <option value="Belarus">Belarus</option>
                        <option value="Belgium">Belgium</option>
                        <option value="Belize">Belize</option>
                        <option value="Benin">Benin</option>
                        <option value="Bermuda">Bermuda</option>
                        <option value="Bhutan">Bhutan</option>
                        <option value="Bolivia">Bolivia</option>
                        <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
                        <option value="Botswana">Botswana</option>
                        <option value="Bouvet Island">Bouvet Island</option>
                        <option value="Brazil">Brazil</option>
                        <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
                        <option value="Brunei">Brunei</option>
                        <option value="Bulgaria">Bulgaria</option>
                        <option value="Burkina Faso">Burkina Faso</option>
                        <option value="Burundi">Burundi</option>
                        <option value="Cambodia">Cambodia</option>
                        <option value="Cameroon">Cameroon</option>
                        <option value="Canada">Canada</option>
                        <option value="Cape Verde">Cape Verde</option>
                        <option value="Cayman Islands">Cayman Islands</option>
                        <option value="Central African Republic">Central African Republic</option>
                        <option value="Chad">Chad</option>
                        <option value="Chile">Chile</option>
                        <option value="China">China</option>
                        <option value="Christmas Island">Christmas Island</option>
                        <option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
                        <option value="Colombia">Colombia</option>
                        <option value="Comoros">Comoros</option>
                        <option value="Republic Of The Congo">Republic Of The Congo</option>
                        <option value="Democratic Republic Of The Congo">Democratic Republic Of The Congo</option>
                        <option value="Cook Islands">Cook Islands</option>
                        <option value="Costa Rica">Costa Rica</option>
                        <option value="Cote D'Ivoire (Ivory Coast)">Cote D'Ivoire (Ivory Coast)</option>
                        <option value="Croatia (Hrvatska)">Croatia (Hrvatska)</option>
                        <option value="Cuba">Cuba</option>
                        <option value="Cyprus">Cyprus</option>
                        <option value="Czech Republic">Czech Republic</option>
                        <option value="Denmark">Denmark</option>
                        <option value="Djibouti">Djibouti</option>
                        <option value="Dominica">Dominica</option>
                        <option value="Dominican Republic">Dominican Republic</option>
                        <option value="East Timor">East Timor</option>
                        <option value="Ecuador">Ecuador</option>
                        <option value="Egypt">Egypt</option>
                        <option value="El Salvador">El Salvador</option>
                        <option value="Equatorial Guinea">Equatorial Guinea</option>
                        <option value="Eritrea">Eritrea</option>
                        <option value="Estonia">Estonia</option>
                        <option value="Ethiopia">Ethiopia</option>
                        <option value="External Territories of Australia">External Territories of Australia</option>
                        <option value="Falkland Islands">Falkland Islands</option>
                        <option value="Faroe Islands">Faroe Islands</option>
                        <option value="Fiji Islands">Fiji Islands</option>
                        <option value="Finland">Finland</option>
                        <option value="France">France</option>
                        <option value="French Guiana">French Guiana</option>
                        <option value="French Polynesia">French Polynesia</option>
                        <option value="French Southern Territories">French Southern Territories</option>
                        <option value="Gabon">Gabon</option>
                        <option value="Gambia The">Gambia The</option>
                        <option value="Georgia">Georgia</option>
                        <option value="Germany">Germany</option>
                        <option value="Ghana">Ghana</option>
                        <option value="Gibraltar">Gibraltar</option>
                        <option value="Greece">Greece</option>
                        <option value="Greenland">Greenland</option>
                        <option value="Grenada">Grenada</option>
                        <option value="Guadeloupe">Guadeloupe</option>
                        <option value="Guam">Guam</option>
                        <option value="Guatemala">Guatemala</option>
                        <option value="Guernsey and Alderney">Guernsey and Alderney</option>
                        <option value="Guinea">Guinea</option>
                        <option value="Guinea-Bissau">Guinea-Bissau</option>
                        <option value="Guyana">Guyana</option>
                        <option value="Haiti">Haiti</option>
                        <option value="Heard and McDonald Islands">Heard and McDonald Islands</option>
                        <option value="Honduras">Honduras</option>
                        <option value="Hong Kong S.A.R.">Hong Kong S.A.R.</option>
                        <option value="Hungary">Hungary</option>
                        <option value="Iceland">Iceland</option>
                        <option value="India">India</option>
                        <option value="Indonesia">Indonesia</option>
                        <option value="Iran">Iran</option>
                        <option value="Iraq">Iraq</option>
                        <option value="Ireland">Ireland</option>
                        <option value="Israel">Israel</option>
                        <option value="Italy">Italy</option>
                        <option value="Jamaica">Jamaica</option>
                        <option value="Japan">Japan</option>
                        <option value="Jersey">Jersey</option>
                        <option value="Jordan">Jordan</option>
                        <option value="Kazakhstan">Kazakhstan</option>
                        <option value="Kenya">Kenya</option>
                        <option value="Kiribati">Kiribati</option>
                        <option value="Korea North">Korea North</option>
                        <option value="Korea South">Korea South</option>
                        <option value="Kuwait">Kuwait</option>
                        <option value="Kyrgyzstan">Kyrgyzstan</option>
                        <option value="Laos">Laos</option>
                        <option value="Latvia">Latvia</option>
                        <option value="Lebanon">Lebanon</option>
                        <option value="Lesotho">Lesotho</option>
                        <option value="Liberia">Liberia</option>
                        <option value="Libya">Libya</option>
                        <option value="Liechtenstein">Liechtenstein</option>
                        <option value="Lithuania">Lithuania</option>
                        <option value="Luxembourg">Luxembourg</option>
                        <option value="Macau S.A.R.">Macau S.A.R.</option>
                        <option value="Macedonia">Macedonia</option>
                        <option value="Madagascar">Madagascar</option>
                        <option value="Malawi">Malawi</option>
                        <option value="Malaysia">Malaysia</option>
                        <option value="Maldives">Maldives</option>
                        <option value="Mali">Mali</option>
                        <option value="Malta">Malta</option>
                        <option value="Man (Isle of)">Man (Isle of)</option>
                        <option value="Marshall Islands">Marshall Islands</option>
                        <option value="Martinique">Martinique</option>
                        <option value="Mauritania">Mauritania</option>
                        <option value="Mauritius">Mauritius</option>
                        <option value="Mayotte">Mayotte</option>
                        <option value="Mexico">Mexico</option>
                        <option value="Micronesia">Micronesia</option>
                        <option value="Moldova">Moldova</option>
                        <option value="Monaco">Monaco</option>
                        <option value="Mongolia">Mongolia</option>
                        <option value="Montserrat">Montserrat</option>
                        <option value="Morocco">Morocco</option>
                        <option value="Mozambique">Mozambique</option>
                        <option value="Myanmar">Myanmar</option>
                        <option value="Namibia">Namibia</option>
                        <option value="Nauru">Nauru</option>
                        <option value="Nepal">Nepal</option>
                        <option value="Netherlands Antilles">Netherlands Antilles</option>
                        <option value="Netherlands The">Netherlands The</option>
                        <option value="New Caledonia">New Caledonia</option>
                        <option value="New Zealand">New Zealand</option>
                        <option value="Nicaragua">Nicaragua</option>
                        <option value="Niger">Niger</option>
                        <option value="Nigeria">Nigeria</option>
                        <option value="Niue">Niue</option>
                        <option value="Norfolk Island">Norfolk Island</option>
                        <option value="Northern Mariana Islands">Northern Mariana Islands</option>
                        <option value="Norway">Norway</option>
                        <option value="Oman">Oman</option>
                        <option value="Pakistan">Pakistan</option>
                        <option value="Palau">Palau</option>
                        <option value="Palestinian Territory Occupied">Palestinian Territory Occupied</option>
                        <option value="Panama">Panama</option>
                        <option value="Papua new Guinea">Papua new Guinea</option>
                        <option value="Paraguay">Paraguay</option>
                        <option value="Peru">Peru</option>
                        <option value="Philippines">Philippines</option>
                        <option value="Pitcairn Island">Pitcairn Island</option>
                        <option value="Poland">Poland</option>
                        <option value="Portugal">Portugal</option>
                        <option value="Puerto Rico">Puerto Rico</option>
                        <option value="Qatar">Qatar</option>
                        <option value="Reunion">Reunion</option>
                        <option value="Romania">Romania</option>
                        <option value="Russia">Russia</option>
                        <option value="Rwanda">Rwanda</option>
                        <option value="Saint Helena">Saint Helena</option>
                        <option value="Saint Kitts And Nevis">Saint Kitts And Nevis</option>
                        <option value="Saint Lucia">Saint Lucia</option>
                        <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
                        <option value="Saint Vincent And The Grenadines">Saint Vincent And The Grenadines</option>
                        <option value="Samoa">Samoa</option>
                        <option value="San Marino">San Marino</option>
                        <option value="Sao Tome and Principe">Sao Tome and Principe</option>
                        <option value="Saudi Arabia">Saudi Arabia</option>
                        <option value="Senegal">Senegal</option>
                        <option value="Serbia">Serbia</option>
                        <option value="Seychelles">Seychelles</option>
                        <option value="Sierra Leone">Sierra Leone</option>
                        <option value="Singapore">Singapore</option>
                        <option value="Slovakia">Slovakia</option>
                        <option value="Slovenia">Slovenia</option>
                        <option value="Smaller Territories of the UK">Smaller Territories of the UK</option>
                        <option value="Solomon Islands">Solomon Islands</option>
                        <option value="Somalia">Somalia</option>
                        <option value="South Africa">South Africa</option>
                        <option value="South Georgia">South Georgia</option>
                        <option value="South Sudan">South Sudan</option>
                        <option value="Spain">Spain</option>
                        <option value="Sri Lanka">Sri Lanka</option>
                        <option value="Sudan">Sudan</option>
                        <option value="Suriname">Suriname</option>
                        <option value="Svalbard And Jan Mayen Islands">Svalbard And Jan Mayen Islands</option>
                        <option value="Swaziland">Swaziland</option>
                        <option value="Sweden">Sweden</option>
                        <option value="Switzerland">Switzerland</option>
                        <option value="Syria">Syria</option>
                        <option value="Taiwan">Taiwan</option>
                        <option value="Tajikistan">Tajikistan</option>
                        <option value="Tanzania">Tanzania</option>
                        <option value="Thailand">Thailand</option>
                        <option value="Togo">Togo</option>
                        <option value="Tokelau">Tokelau</option>
                        <option value="Tonga">Tonga</option>
                        <option value="Trinidad And Tobago">Trinidad And Tobago</option>
                        <option value="Tunisia">Tunisia</option>
                        <option value="Turkey">Turkey</option>
                        <option value="Turkmenistan">Turkmenistan</option>
                        <option value="Turks And Caicos Islands">Turks And Caicos Islands</option>
                        <option value="Tuvalu">Tuvalu</option>
                        <option value="Uganda">Uganda</option>
                        <option value="Ukraine">Ukraine</option>
                        <option value="United Arab Emirates">United Arab Emirates</option>
                        <option value="United Kingdom">United Kingdom</option>
                        <option value="United States">United States</option>
                        <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
                        <option value="Uruguay">Uruguay</option>
                        <option value="Uzbekistan">Uzbekistan</option>
                        <option value="Vanuatu">Vanuatu</option>
                        <option value="Vatican City State (Holy See)">Vatican City State (Holy See)</option>
                        <option value="Venezuela">Venezuela</option>
                        <option value="Vietnam">Vietnam</option>
                        <option value="Virgin Islands (British)">Virgin Islands (British)</option>
                        <option value="Virgin Islands (US)">Virgin Islands (US)</option>
                        <option value="Wallis And Futuna Islands">Wallis And Futuna Islands</option>
                        <option value="Western Sahara">Western Sahara</option>
                        <option value="Yemen">Yemen</option>
                        <option value="Yugoslavia">Yugoslavia</option>
                        <option value="Zambia">Zambia</option>
                        <option value="Zimbabwe">Zimbabwe</option>
                     </select>
                     <div class="select-styled">Select Country</div>
                     <ul class="select-options">
                        <li rel="Select Country">Select Country</li>
                        <li rel="Afghanistan">Afghanistan</li>
                        <li rel="Albania">Albania</li>
                        <li rel="Algeria">Algeria</li>
                        <li rel="American Samoa">American Samoa</li>
                        <li rel="Andorra">Andorra</li>
                        <li rel="Angola">Angola</li>
                        <li rel="Anguilla">Anguilla</li>
                        <li rel="Antarctica">Antarctica</li>
                        <li rel="Antigua And Barbuda">Antigua And Barbuda</li>
                        <li rel="Argentina">Argentina</li>
                        <li rel="Armenia">Armenia</li>
                        <li rel="Aruba">Aruba</li>
                        <li rel="Australia">Australia</li>
                        <li rel="Austria">Austria</li>
                        <li rel="Azerbaijan">Azerbaijan</li>
                        <li rel="Bahamas The">Bahamas The</li>
                        <li rel="Bahrain">Bahrain</li>
                        <li rel="Bangladesh">Bangladesh</li>
                        <li rel="Barbados">Barbados</li>
                        <li rel="Belarus">Belarus</li>
                        <li rel="Belgium">Belgium</li>
                        <li rel="Belize">Belize</li>
                        <li rel="Benin">Benin</li>
                        <li rel="Bermuda">Bermuda</li>
                        <li rel="Bhutan">Bhutan</li>
                        <li rel="Bolivia">Bolivia</li>
                        <li rel="Bosnia and Herzegovina">Bosnia and Herzegovina</li>
                        <li rel="Botswana">Botswana</li>
                        <li rel="Bouvet Island">Bouvet Island</li>
                        <li rel="Brazil">Brazil</li>
                        <li rel="British Indian Ocean Territory">British Indian Ocean Territory</li>
                        <li rel="Brunei">Brunei</li>
                        <li rel="Bulgaria">Bulgaria</li>
                        <li rel="Burkina Faso">Burkina Faso</li>
                        <li rel="Burundi">Burundi</li>
                        <li rel="Cambodia">Cambodia</li>
                        <li rel="Cameroon">Cameroon</li>
                        <li rel="Canada">Canada</li>
                        <li rel="Cape Verde">Cape Verde</li>
                        <li rel="Cayman Islands">Cayman Islands</li>
                        <li rel="Central African Republic">Central African Republic</li>
                        <li rel="Chad">Chad</li>
                        <li rel="Chile">Chile</li>
                        <li rel="China">China</li>
                        <li rel="Christmas Island">Christmas Island</li>
                        <li rel="Cocos (Keeling) Islands">Cocos (Keeling) Islands</li>
                        <li rel="Colombia">Colombia</li>
                        <li rel="Comoros">Comoros</li>
                        <li rel="Republic Of The Congo">Republic Of The Congo</li>
                        <li rel="Democratic Republic Of The Congo">Democratic Republic Of The Congo</li>
                        <li rel="Cook Islands">Cook Islands</li>
                        <li rel="Costa Rica">Costa Rica</li>
                        <li rel="Cote D'Ivoire (Ivory Coast)">Cote D'Ivoire (Ivory Coast)</li>
                        <li rel="Croatia (Hrvatska)">Croatia (Hrvatska)</li>
                        <li rel="Cuba">Cuba</li>
                        <li rel="Cyprus">Cyprus</li>
                        <li rel="Czech Republic">Czech Republic</li>
                        <li rel="Denmark">Denmark</li>
                        <li rel="Djibouti">Djibouti</li>
                        <li rel="Dominica">Dominica</li>
                        <li rel="Dominican Republic">Dominican Republic</li>
                        <li rel="East Timor">East Timor</li>
                        <li rel="Ecuador">Ecuador</li>
                        <li rel="Egypt">Egypt</li>
                        <li rel="El Salvador">El Salvador</li>
                        <li rel="Equatorial Guinea">Equatorial Guinea</li>
                        <li rel="Eritrea">Eritrea</li>
                        <li rel="Estonia">Estonia</li>
                        <li rel="Ethiopia">Ethiopia</li>
                        <li rel="External Territories of Australia">External Territories of Australia</li>
                        <li rel="Falkland Islands">Falkland Islands</li>
                        <li rel="Faroe Islands">Faroe Islands</li>
                        <li rel="Fiji Islands">Fiji Islands</li>
                        <li rel="Finland">Finland</li>
                        <li rel="France">France</li>
                        <li rel="French Guiana">French Guiana</li>
                        <li rel="French Polynesia">French Polynesia</li>
                        <li rel="French Southern Territories">French Southern Territories</li>
                        <li rel="Gabon">Gabon</li>
                        <li rel="Gambia The">Gambia The</li>
                        <li rel="Georgia">Georgia</li>
                        <li rel="Germany">Germany</li>
                        <li rel="Ghana">Ghana</li>
                        <li rel="Gibraltar">Gibraltar</li>
                        <li rel="Greece">Greece</li>
                        <li rel="Greenland">Greenland</li>
                        <li rel="Grenada">Grenada</li>
                        <li rel="Guadeloupe">Guadeloupe</li>
                        <li rel="Guam">Guam</li>
                        <li rel="Guatemala">Guatemala</li>
                        <li rel="Guernsey and Alderney">Guernsey and Alderney</li>
                        <li rel="Guinea">Guinea</li>
                        <li rel="Guinea-Bissau">Guinea-Bissau</li>
                        <li rel="Guyana">Guyana</li>
                        <li rel="Haiti">Haiti</li>
                        <li rel="Heard and McDonald Islands">Heard and McDonald Islands</li>
                        <li rel="Honduras">Honduras</li>
                        <li rel="Hong Kong S.A.R.">Hong Kong S.A.R.</li>
                        <li rel="Hungary">Hungary</li>
                        <li rel="Iceland">Iceland</li>
                        <li rel="India">India</li>
                        <li rel="Indonesia">Indonesia</li>
                        <li rel="Iran">Iran</li>
                        <li rel="Iraq">Iraq</li>
                        <li rel="Ireland">Ireland</li>
                        <li rel="Israel">Israel</li>
                        <li rel="Italy">Italy</li>
                        <li rel="Jamaica">Jamaica</li>
                        <li rel="Japan">Japan</li>
                        <li rel="Jersey">Jersey</li>
                        <li rel="Jordan">Jordan</li>
                        <li rel="Kazakhstan">Kazakhstan</li>
                        <li rel="Kenya">Kenya</li>
                        <li rel="Kiribati">Kiribati</li>
                        <li rel="Korea North">Korea North</li>
                        <li rel="Korea South">Korea South</li>
                        <li rel="Kuwait">Kuwait</li>
                        <li rel="Kyrgyzstan">Kyrgyzstan</li>
                        <li rel="Laos">Laos</li>
                        <li rel="Latvia">Latvia</li>
                        <li rel="Lebanon">Lebanon</li>
                        <li rel="Lesotho">Lesotho</li>
                        <li rel="Liberia">Liberia</li>
                        <li rel="Libya">Libya</li>
                        <li rel="Liechtenstein">Liechtenstein</li>
                        <li rel="Lithuania">Lithuania</li>
                        <li rel="Luxembourg">Luxembourg</li>
                        <li rel="Macau S.A.R.">Macau S.A.R.</li>
                        <li rel="Macedonia">Macedonia</li>
                        <li rel="Madagascar">Madagascar</li>
                        <li rel="Malawi">Malawi</li>
                        <li rel="Malaysia">Malaysia</li>
                        <li rel="Maldives">Maldives</li>
                        <li rel="Mali">Mali</li>
                        <li rel="Malta">Malta</li>
                        <li rel="Man (Isle of)">Man (Isle of)</li>
                        <li rel="Marshall Islands">Marshall Islands</li>
                        <li rel="Martinique">Martinique</li>
                        <li rel="Mauritania">Mauritania</li>
                        <li rel="Mauritius">Mauritius</li>
                        <li rel="Mayotte">Mayotte</li>
                        <li rel="Mexico">Mexico</li>
                        <li rel="Micronesia">Micronesia</li>
                        <li rel="Moldova">Moldova</li>
                        <li rel="Monaco">Monaco</li>
                        <li rel="Mongolia">Mongolia</li>
                        <li rel="Montserrat">Montserrat</li>
                        <li rel="Morocco">Morocco</li>
                        <li rel="Mozambique">Mozambique</li>
                        <li rel="Myanmar">Myanmar</li>
                        <li rel="Namibia">Namibia</li>
                        <li rel="Nauru">Nauru</li>
                        <li rel="Nepal">Nepal</li>
                        <li rel="Netherlands Antilles">Netherlands Antilles</li>
                        <li rel="Netherlands The">Netherlands The</li>
                        <li rel="New Caledonia">New Caledonia</li>
                        <li rel="New Zealand">New Zealand</li>
                        <li rel="Nicaragua">Nicaragua</li>
                        <li rel="Niger">Niger</li>
                        <li rel="Nigeria">Nigeria</li>
                        <li rel="Niue">Niue</li>
                        <li rel="Norfolk Island">Norfolk Island</li>
                        <li rel="Northern Mariana Islands">Northern Mariana Islands</li>
                        <li rel="Norway">Norway</li>
                        <li rel="Oman">Oman</li>
                        <li rel="Pakistan">Pakistan</li>
                        <li rel="Palau">Palau</li>
                        <li rel="Palestinian Territory Occupied">Palestinian Territory Occupied</li>
                        <li rel="Panama">Panama</li>
                        <li rel="Papua new Guinea">Papua new Guinea</li>
                        <li rel="Paraguay">Paraguay</li>
                        <li rel="Peru">Peru</li>
                        <li rel="Philippines">Philippines</li>
                        <li rel="Pitcairn Island">Pitcairn Island</li>
                        <li rel="Poland">Poland</li>
                        <li rel="Portugal">Portugal</li>
                        <li rel="Puerto Rico">Puerto Rico</li>
                        <li rel="Qatar">Qatar</li>
                        <li rel="Reunion">Reunion</li>
                        <li rel="Romania">Romania</li>
                        <li rel="Russia">Russia</li>
                        <li rel="Rwanda">Rwanda</li>
                        <li rel="Saint Helena">Saint Helena</li>
                        <li rel="Saint Kitts And Nevis">Saint Kitts And Nevis</li>
                        <li rel="Saint Lucia">Saint Lucia</li>
                        <li rel="Saint Pierre and Miquelon">Saint Pierre and Miquelon</li>
                        <li rel="Saint Vincent And The Grenadines">Saint Vincent And The Grenadines</li>
                        <li rel="Samoa">Samoa</li>
                        <li rel="San Marino">San Marino</li>
                        <li rel="Sao Tome and Principe">Sao Tome and Principe</li>
                        <li rel="Saudi Arabia">Saudi Arabia</li>
                        <li rel="Senegal">Senegal</li>
                        <li rel="Serbia">Serbia</li>
                        <li rel="Seychelles">Seychelles</li>
                        <li rel="Sierra Leone">Sierra Leone</li>
                        <li rel="Singapore">Singapore</li>
                        <li rel="Slovakia">Slovakia</li>
                        <li rel="Slovenia">Slovenia</li>
                        <li rel="Smaller Territories of the UK">Smaller Territories of the UK</li>
                        <li rel="Solomon Islands">Solomon Islands</li>
                        <li rel="Somalia">Somalia</li>
                        <li rel="South Africa">South Africa</li>
                        <li rel="South Georgia">South Georgia</li>
                        <li rel="South Sudan">South Sudan</li>
                        <li rel="Spain">Spain</li>
                        <li rel="Sri Lanka">Sri Lanka</li>
                        <li rel="Sudan">Sudan</li>
                        <li rel="Suriname">Suriname</li>
                        <li rel="Svalbard And Jan Mayen Islands">Svalbard And Jan Mayen Islands</li>
                        <li rel="Swaziland">Swaziland</li>
                        <li rel="Sweden">Sweden</li>
                        <li rel="Switzerland">Switzerland</li>
                        <li rel="Syria">Syria</li>
                        <li rel="Taiwan">Taiwan</li>
                        <li rel="Tajikistan">Tajikistan</li>
                        <li rel="Tanzania">Tanzania</li>
                        <li rel="Thailand">Thailand</li>
                        <li rel="Togo">Togo</li>
                        <li rel="Tokelau">Tokelau</li>
                        <li rel="Tonga">Tonga</li>
                        <li rel="Trinidad And Tobago">Trinidad And Tobago</li>
                        <li rel="Tunisia">Tunisia</li>
                        <li rel="Turkey">Turkey</li>
                        <li rel="Turkmenistan">Turkmenistan</li>
                        <li rel="Turks And Caicos Islands">Turks And Caicos Islands</li>
                        <li rel="Tuvalu">Tuvalu</li>
                        <li rel="Uganda">Uganda</li>
                        <li rel="Ukraine">Ukraine</li>
                        <li rel="United Arab Emirates">United Arab Emirates</li>
                        <li rel="United Kingdom">United Kingdom</li>
                        <li rel="United States">United States</li>
                        <li rel="United States Minor Outlying Islands">United States Minor Outlying Islands</li>
                        <li rel="Uruguay">Uruguay</li>
                        <li rel="Uzbekistan">Uzbekistan</li>
                        <li rel="Vanuatu">Vanuatu</li>
                        <li rel="Vatican City State (Holy See)">Vatican City State (Holy See)</li>
                        <li rel="Venezuela">Venezuela</li>
                        <li rel="Vietnam">Vietnam</li>
                        <li rel="Virgin Islands (British)">Virgin Islands (British)</li>
                        <li rel="Virgin Islands (US)">Virgin Islands (US)</li>
                        <li rel="Wallis And Futuna Islands">Wallis And Futuna Islands</li>
                        <li rel="Western Sahara">Western Sahara</li>
                        <li rel="Yemen">Yemen</li>
                        <li rel="Yugoslavia">Yugoslavia</li>
                        <li rel="Zambia">Zambia</li>
                        <li rel="Zimbabwe">Zimbabwe</li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="col-lg-6 col-md-6 col-12">
               <label for="">Pickup Details</label>
               <textarea name="information"></textarea>
            </div>
            <div class="col-lg-6 col-md-12 col-12">
               <label for="">Other Details</label>
               <textarea name="other_details"></textarea>
            </div>
         </div>
         <div class="col-lg-12 col-md-12 col-12">
            <button class="primary__button" type="submit">Confirm Booking</button>
         </div>

      </form>
   </div>
</section>

<?php require('inc/footer.php') ?>